spring.application.name=study 
server.port=8091
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name =com.mysql.jdbc.Driver
spring.datasource.url: r2dbc:postgresql://localhost:5432/study?schema=learn
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

